### ISSUE TITLE
Prompt for node deposit confirmation if eth2 client is not synced

### ISSUE THREAD

**Issue by moles1** [rocket-pool/smartnode#110]
Making a node deposit and creating a minipool can potentially result in having a staking validator before the eth2 client is fully synced and the validator is able to perform its duties.

Add a check for eth2 sync status to the `rocketpool node deposit` command. If the eth2 client is not synced yet, prompt the user to confirm if they would like to continue (also add a CLI flag to override this prompt and continue automatically; or simply use the existing `-y` flag).

**Comment by jclapis** [comment]
Added in #146
