### ISSUE TITLE
Skip nETH delay if sufficient ETH balance has been received

### ISSUE THREAD

**Issue by darcius** [rocket-pool/smartnode#118]
With this update to the smart contracts https://github.com/rocket-pool/rocketpool/commit/1ac3cf181f13d5bd1de549916fc0b77c3e86c259 - The nETH withdrawal delay can be skipped if the minipool has received enough ETH to cover the required amount to destroy it.

So we'll need to update the CLI to reflect this. The nETH delay shouldn't be shown if the minipools current ETH balance is >= the required final balance.

**Comment by jclapis** [comment]
Closed since nETH has been removed.
