### ISSUE TITLE
The smart node consumed the entire request quota on a free Infura account in less than an hour.

### ISSUE THREAD

**Issue by zah** [rocket-pool/smartnode#126]
I've tried to configure my RocketPool node with a free Infura account. In less than an hour, the node performed over 100K request which depleted my request quota. The bulk of the requests were `eth_calls` which must be originating from the smart node, because Nimbus (the eth2 client in use) is not using this type of request for anything. 

```
eth_call                 98,472  92.24%
eth_getBlockByNumber      4,647   4.35%
eth_getBlockByHash        1,422   1.33%
eth_getTransactionReceipt 1,268   1.19%
eth_syncing                 676   0.63%
eth_getLogs                 189   0.18%
eth_getCode                  36   0.03%
eth_getBalance               23   0.02%
eth_estimateGas              12   0.01%
```

Once the quota is exceeded, most commands start to fail:

```bash
$ rocketpool node status

Could not get node status: daily request count exceeded, request rate limited
```

**Comment by moles1** [comment]
Hey, thanks for reporting this. Just wanted to confirm, did this occur after your node was inducted as a member of the oracle DAO? Oracle DAO nodes need to query quite a lot of RP network state to make various calculations and report data back to RP contracts, so this would make sense in that context.

If not, then this isn't really expected; a regular node should not make that number of calls.

**Comment by jclapis** [comment]
Closing because I believe this was a consequence of ODAO activites.
