### ISSUE TITLE
Node deposit needs to warn people if eth2 isn't synced yet

### ISSUE THREAD

**Issue by jclapis** [rocket-pool/smartnode#140]
Context: https://discord.com/channels/405159462932971535/468923220607762485/837072179770032148

**Comment by stradivarius96** [comment]
Agree with this issue. I set up my first node last week and it looked like all the services were up and happy. I node deposited with my eth2 not finished syncing and got missed assignment penalties for a few days before it was finally caught up. Definitely would be something good to warn about.

**Comment by jclapis** [comment]
Fixed in #142.
