### ISSUE TITLE
Add routes for metrics to the CLI

### ISSUE THREAD

**Issue by jclapis** [rocket-pool/smartnode#141]
Here's what people have requested:

- A route to see the eth1 and eth2 sync status (e.g. percent)
- The current collateral percentage of staked RPL on the node

**Comment by beetis** [comment]
It would be handy for a Node Operator to be able to quickly check their RPL collateral %, especially for those that may have several minipools running. The % can be inferred from the data available in `rocketpool node status` but I think a straightforward display of the critical collateralization % would be a nice luxury.

**Comment by jclapis** [comment]
Added in #146.
