### ISSUE TITLE
[FR] Add Support for Fallback eth1 Clients

### ISSUE THREAD

**Issue by jclapis** [rocket-pool/smartnode#149]
Some of the eth2 clients have the ability to support fallback eth1 clients for deposit information. This would be useful to support, for example, when you're pruning geth and need to take it down for a few hours.

To do this, here's what needs to happen:
- Modify the `service config` interview to ask for it (if the selected eth2 client supports it)
- Add some variables to `docker-compose` and the launch scripts to support the fallback command line args for each client
- Add support in `smartnode` for those additional variable(s)
- Add support in the smartnode *itself* for the fallback client, so whenever you try to do something, it goes through the list of eth1 endpoints until it finds one that works

**Comment by rocketpeon** [comment]
Collating docs for each of the 4 clients for this:

**Prysm**
Add `**--fallback-web3provider=https://goerli.infura.io/v3/YOUR-PROJECT-ID**` to CLI params
https://docs.prylabs.network/docs/prysm-usage/setup-eth1#adding-fallback-eth1-nodes

**Lighthouse**
Append bolded portion `--eth1-endpoints $ETH1_PROVIDER**,https://goerli.infura.io/v3/YOUR-PROJECT-ID**` to CLI params
https://lighthouse-book.sigmaprime.io/redundancy.html#redundant-eth1-nodes 

**Nimbus**
Add additional `--web3-url https://goerli.infura.io/v3/YOUR-PROJECT-ID` to CLI params
https://github.com/status-im/nimbus-eth2/releases/tag/v1.1.0

**Teku**
Append bolded portion `--eth1-endpoint $ETH1_PROVIDER**,https://goerli.infura.io/v3/YOUR-PROJECT-ID**` to CLI params
https://docs.teku.consensys.net/en/latest/Reference/CLI/CLI-Syntax/#eth1-endpoint-eth1-endpoints

**Comment by jclapis** [comment]
Added in v1.2.0
