### ISSUE TITLE
Error while registering node: "Method not found" - Support Besu as ETH1 client

### ISSUE THREAD

**Issue by C8395** [rocket-pool/smartnode#164]
I am trying to set up rocketpool as an independent node operator (Ubuntu 20.04 LTS, Goerli + Prater network). Setup mostly followed documentation's "Native Mode" path. Eth1 (Besu), Eth2 (Teku) clients are setup independently and running as systemd services and both synced fully. All rocketpool related files are set up in the Linux standard "/var/lib/rocketpool" directory. Wallets are initialized and put some Goerli ETH in it. 

rp node status: All good
rp node register: error "_Could not register node: Method not found_".
rp wallet status: All good
rp faucet withdraw-rpl: error "_Could not withdraw RPL from faucet: Method not found_".

At Discord #support channel, jcrtp.eth answered my question on this: 
"Today at 11:35 AM Method not found is probably referring to one of the Geth-only nonstandard API calls that the Smartnode does. I'm going to work on removing them when I add more first-class ETH1 client support. I'm not sure exactly which method is missing but I'll find out"

**Comment by jclapis** [comment]
I believe this was fixed with v1.1.0 - can you try it with Besu and confirm?
