### ISSUE TITLE
[FR] Add support for naming beaconcha.in minipools. 

### ISSUE THREAD

**Issue by htimsk** [rocket-pool/smartnode#165]
Beaconcha.in allows node operators to name their minipools (validators) on their website. For example, https://beaconcha.in/validator/244323#attestations can be named _Arugula_ by clicking the Name Validator button. 

In order to save any validator details, the NO will need to provide a signed message from the eth1 node wallet account that sent the first valid deposit for verification. Currently, beaconcha.in support signatures generated with MyCrypto and MyEtherWallet.

The signature text MUST CONTAIN the string beaconcha.in.

see https://discord.com/channels/405159462932971535/704214707904446535/907809792985292800

**Comment by Sonixier** [comment]
This is possible now with `rocketpool node sign-message`

**Comment by 0xfornax** [comment]
@jclapis this one could be closed. I forgot to link after sending the PR.

**Comment by xrchz** [comment]
I guess we could also keep it open though.
