### ISSUE TITLE
[FR] Add rocketpool node sync committee to CLI or Granfana

### ISSUE THREAD

**Issue by htimsk** [rocket-pool/smartnode#170]
Add a command for NO to determine if one of their minipools is assigned sync committee duties. This information will be used when performing software updates or OS updates that require a reboot. 

It can be based off of the following script: https://www.coincashew.com/coins/overview-eth/guide-or-how-to-setup-a-validator-on-eth2-mainnet/how-to-check-my-eth-validators-sync-committee-duties

**Comment by jclapis** [comment]
Added with Smartnode v1.2.0 and Dashboard v1.1.0.
