### ISSUE TITLE
[FR] `rocketpool wallet recover` should prompt word-at-a-time, and validate the input against the wordlist.

### ISSUE THREAD

**Issue by jshufro** [rocket-pool/smartnode#200]
It's pretty frustrating trying to type 24 words with spaces into a terminal that is masking the input, only to find a small typo means you must restart from the beginning.

Instead, just prompt the user for the length of their phrase, and then prompt N times for each word, validating as they go. If a word doesn't match the word list, re-prompt for that word.

Edit: While we're at it, we should allow input of _just_ the first 4 characters of each word from the wordlist, since that is enough to distinguish them, and many offline backup methods only retain 4 characters max per word (some words are only 3 characters long, eg, `ill`, and also need to work)

**Comment by blinc117** [comment]
Also add for the test function
