### ISSUE TITLE
A trailing space in the mnemonic recovers a different wallet

### ISSUE THREAD

**Issue by jshufro** [rocket-pool/smartnode#201]
Observed when messing around on prater:

`rocketpool wallet recover` recovers two different wallets for the same seed phrase if entered with/without a trailing space.

Best guess is that the crypto library interprets the trailing space as an empty 25th word, or something.

Either way, the user-space code should probably trim the input.

**Comment by jclapis** [comment]
Fixed in 418cb86 for now, though #200 is better UX so we should do that relatively soon.
