### ISSUE TITLE
Improper key management leads to unintended slashing (Validator 391311)

### ISSUE THREAD

**Issue by superphiz** [rocket-pool/smartnode#212]
A Rocket Pool node operator was recently slashed after attempting to wipe keys but failing to clear the keys properly. While it is regarded as user error, Rocket Pool ought to learn from these user errors and prevent similar events in the future.

[Beaconcha.in link to slashed validator #391311](https://beaconcha.in/validator/391311)

[Discord dicussion link - Rocket Pool discord, #Trading channel](https://discord.com/channels/405159462932971535/405163713063288832/990325863235063838)

[Screenshot of discord discussion](https://i.ibb.co/cxnsRsN/Screenshot-from-2022-06-25-16-03-36.png)

Here are two suggestions that could have prevented this loss:

* Ensure the integrity of all 4 keystores. Maybe maintain a lockfile so that only one client (of any type) is running.
* Implement a wallet purge feature like `rocketpool wallet purge` that fully removes any trace of user wallets, this removes the need for the user to attempt manual removal.

**Comment by TheSlashedNo** [comment]
As the node operator I can add a few details.

Let me preface this by saying it was 100% my error and I'm not blaming the smartnode stack in any way. I know the smartnode stack manages the keys and to properly delete them, I should have either used a smartnode command (`rocketpool service terminate` I guess) or just wiped the whole `.rocketpool/data` directory. 

What caught me out is that the smartnode stack had copied the validator keys from the lighthouse directory `.rocketpool/data/validators/lighthouse` to `.rocketpool/data/validators/nimbus`. I **absolutely did not expect** that copies of the keys exist.

Interestingly, they keys where only copied to the nimbus directory, not in teku oder prysm. Maybe I did select nimbus in the TUI once during setup before going for lighthouse, but I certainly never synced or ran nimbus. So not sure how they got there.

As for potential improvements:

- A `rocketpool wallet purge` seems useful.
- Avoid having copies of keys, i.e. only ever keep the keys in that one CL that is selected. Just as a best practice to only have keys in one location.

**Comment by 0xfornax** [comment]
I'm on it @superphiz
`rocketpool wallet purge-keys` soon™️
