### ISSUE TITLE
[FR] Add support for ENS domains.

### ISSUE THREAD

**Issue by 0xobjectObject** [rocket-pool/smartnode#224]
Now that we're encouraging people to delegate their votes, it would be nice if they could enter an ENS domain instead of having to copy/paste a long address.
Would be a QoL improvement for `send` and `w` as well, but i think it's most important for `sv`.

**Comment by minsguy** [comment]
I agree - this would be a "nice to have" feature.  At a minimum, I think it would be good to note in the Medium article that ens names will not currently work - I almost tried using one before I checked with Object.  Thanks!

**Comment by jclapis** [comment]
Fixed in v1.7.
