### ISSUE TITLE
Show smoothing pool contract address somewhere when joined smoothing pool

### ISSUE THREAD

**Issue by pk910** [rocket-pool/smartnode#226]
Heya,

The rocketpool-cli should show the smoothing pool contract address in `node status` when the smoothing pool has been joined.

I'm running rocket pool in native mode, so the rp node cannot adjust the validator client flags itself.
There was no advice during the `node join-smoothing-pool` process that the fee-recipient needs to be changed.
I just got suspect of that line `NOTE: This process will restart your node's validator client.` and found the contract address for goerli myself (0xd4E96eF8eee8678dBFf4d535E033Ed1a4F7605b7) by reading source code...
It would be very helpful if it's just displayed in `node status`.

**Comment by jclapis** [comment]
Done:
![image](https://user-images.githubusercontent.com/627896/184831775-258b95e6-aa08-4e57-8951-86011da0d215.png)

![image](https://user-images.githubusercontent.com/627896/184831832-1c8fdc04-c5ca-4363-ba3b-e641a69a9b49.png)

This will be in v1.5.1.
