### ISSUE TITLE
node claim-rewards with >150% collateral states wrong percentage in option 2

### ISSUE THREAD

**Issue by risasoft** [rocket-pool/smartnode#234]
When claiming reward with over collateralized node, the prompt does not calculate the percentage in option 2.

Expected:
Prompt should read `2: All 43.322756 RPL, which will bring you to 165.29% collateral`

Actual:
Prompt reads `2: All 41.224925 RPL, which will bring you to 0.00% collateral`

Code in question: https://github.com/rocket-pool/smartnode/blob/57702055bab4b0fc2ac3fa5cbe94bc9876278195/rocketpool-cli/node/claim-rewards.go#L375

![image](https://user-images.githubusercontent.com/98934812/188030526-6743f2e9-bb45-4c39-bebf-72a87ffb5dba.png)

**Comment by jclapis** [comment]
Yep I've seen a few reports of this, I'll have it fixed for the next feature release. Thanks for making the issue!

**Comment by risasoft** [comment]
No rush! It's just a display issue and I'm sure there are higher priorities right now. Figured I would get this one on the todo list.
