### ISSUE TITLE
vanity miner returns salt that doesn't create the correct address

### ISSUE THREAD

**Issue by superphiz** [rocket-pool/smartnode#235]
rocketpool smartnode version 1.6.2

attempting to create a vanity address using a string like `rocketpool m v -p 0x000 -a 16` returns a salt, but when this salt is used to create a node using `r n d -l 0x???` the derived address doesn't match the target vanity prefix. Tested and failed on mainnet and prater.

**Comment by jclapis** [comment]
Sorry about that, vestige of Redstone - fixed in 377632b096cb1ac49b158574bb2cd7ac8aecbc08.
