### ISSUE TITLE
MEV-boost for hybrid mode users could be marginally improved

### ISSUE THREAD

**Issue by jshufro** [rocket-pool/smartnode#237]
There's sort of two ways a hybrid mode (_not_ reverse hybrid) user might want to use mev-boost in smartnode:

1. Locally managed, API port exposed. This way my external BN can use my smartnode mev-boost.
2. Externally managed, VC simply needs to enable builder proposal mode. This is probably the more common use-case.

Right now 1) works great, but 2) could be marginally improved:

When setting up externally-managed MEV boost, I currently wouldn't need to populate the "External URL". However, `start-vc.sh` only checks the population of this field, so leaving it blank would _not actually enable MEV boost_:
```bash
    if [ ! -z "$MEV_BOOST_URL" ]; then
        CMD="$CMD --enable-builder"
    fi
```

I'd suggest the addition of a new env variable that tracks whether mev-boost is enabled, and keying `start-vc.sh` off of it.

As for the "External URL" field, I think we should either hide it from the TUI when the BN/EC are also externally managed, or leave it and tweak the guides to direct people to expose the api port of the mev-boost container on whatever machine is running mev-boost (if not natively). If we decide to leave "External URL", `rocketpool node sync` should hit `/eth/v1/builder/status` (undocumented feature presently) at the mev-boost external URL (thus the need for the exposed port), which responds `{}` 200 OK if at least 1 relay is "healthy".

**Comment by fmoledina** [comment]
Looks like this was captured in https://github.com/rocket-pool/smartnode-install/commit/eb5eda47f3181b31b81e69d862014b74082e9fd0.
