### ISSUE TITLE
Support EIP1559 transactions in `api node sign` command

### ISSUE THREAD

**Issue by kanewallmann** [rocket-pool/smartnode#239]
EIP1559 transactions are not supported by the `api node sign` command. I believe it's because we are using `NewEIP155Signer` instead of `NewLondonSigner` here: https://github.com/rocket-pool/smartnode/blob/c4dd69c105f7ff3558bbe8d6dbe4c1873968a22a/shared/services/wallet/wallet.go#L272

When invoking the command with a type 0x02 transaction the following is outputed:

```
{"status":"error","error":"Error signing TX [...]: Error signing TX: transaction type not supported","signedData":""}
```

**Comment by jclapis** [comment]
Fixed in v1.7.
