### ISSUE TITLE
mev-boost docker container fails to start

### ISSUE THREAD

**Issue by lennartack** [rocket-pool/smartnode#240]
My newly created mev-boost container doesn't boot and keeps restarting. Running Rocket Pool Smartnode 1.6.3.

From `docker ps`:
```
CONTAINER ID   IMAGE                                    COMMAND                  CREATED          STATUS                         PORTS                                                                                                         NAMES
19603fa86b21   flashbots/mev-boost:v0.8.2               "sh /setup/start-mev…"   10 minutes ago   Restarting (2) 3 seconds ago                                                                                                                 rocketpool_mev-boost
```

The docker logs (attached) report various "SIGILL: illegal instruction".
[mev-boost.txt](https://github.com/rocket-pool/smartnode/files/9574587/mev-boost.txt)

**Comment by lennartack** [comment]
Sorry for forgetting to Google this. This is probably the same bug as https://github.com/flashbots/mev-boost/issues/256. Apparently I need a portable build.

**Comment by jclapis** [comment]
v1.7 will automatically detect if your CPU can run a `modern` container or needs a `portable` one automatically, so this should be resolved.
