### ISSUE TITLE
[FR] Additional MEV Relays

### ISSUE THREAD

**Issue by risasoft** [rocket-pool/smartnode#242]
It would be nice to have some more relays available. Here are the ones I know, but their APIs need to be vetted for compatibility:

Blocknative: https://0x9000009807ed12c1f08bf4e81c6da3ba8e3fc3d953898ce0102433094e5f22f21102ec057841fcb81978ed1ea0fa8246@builder-relay-mainnet.blocknative.com

Manifold: https://0x98650451ba02064f7b000f5768cf0cf4d4e492317d82871bdc87ef841a0743f69f0f1eea11168503240ac35d101c9135@mainnet-relay.securerpc.com

Eden: https://0xb3ee7afcf27f1f1259ac1787876318c6584ee353097a50ed84f51a1f21a323b3736f271a895c7ce918c038e4265918be@relay.edennetwork.io

**Comment by jclapis** [comment]
I'll be adding Blocknative and Eden into v1.6.4. We're still working on Manifold.

**Comment by jclapis** [comment]
Blocknative and Eden have been added. Manifold can be, predicated on their coordination with the team.
