### ISSUE TITLE
Add support for docker-compose-plugin

### ISSUE THREAD

**Issue by eth2353** [rocket-pool/smartnode#244]
Would it be possible to optionally switch/override the `docker-compose` base command for `docker compose` somehow?

I have docker compose installed on my system in the way described [in Docker's docs](https://docs.docker.com/compose/install/linux/) - meaning as a "Compose plugin" to the Docker CLI package. This means I run compose commands like this - `docker compose ps` - instead of `docker-compose ps`. ( In their docs this new "space compose" syntax is even considered standard, see [here](https://docs.docker.com/compose/install/other/#install-compose-standalone) )

Looks like smartnode does not currently support this way of running docker compose - `docker-compose: not found`.

I suppose I could fix this locally by using an alias but I wanted to ask you if there might be a better way of doing this or if you plan to add support for this.

Thank you!

**Comment by jclapis** [comment]
Fixed in v1.7.
