### ISSUE TITLE
Post node migration, rocketpool network stats are broken

### ISSUE THREAD

**Issue by jshufro** [rocket-pool/smartnode#252]
This issue came up in #support today and was not very easy to diagnose so I'm filing a ticket to make sure I don't miss any details.

## Reproduction
1. Run a validator for at least 1 rewards interval
2. Claim rewards for that interval
3. Migrate to a new node
4. Observe that some of the metrics are missing from Grafana (namely, "Your Beacon Chain Earnings" and a few others)

## Cause
```
node_1           | 2022/09/27 23:29:12 Error calculating lifetime node rewards: rewards file /.rocketpool/data/rewards-trees/rp-rewards-mainnet-0.json doesn't exist but interval 0 was claimed
```

Why does this file not exist? Well... `downloadRewardsTrees`...
```go
        // Get the unclaimed intervals
        unclaimed, _, err := rprewards.GetClaimStatus(d.rp, nodeAccount.Address)
        if err != nil {
                return err
        }

        // Check for missing intervals
        missingIntervals := []rprewards.IntervalInfo{}
        for _, interval := range unclaimed {
                intervalInfo, err := rprewards.GetIntervalInfo(d.rp, d.cfg, nodeAccount.Address, interval)
                if err != nil {
                        return err
                }
                if !intervalInfo.TreeFileExists {
                        d.log.Printlnf("You are missing the rewards tree file for interval %d.", intervalInfo.Index)
                        missingIntervals = append(missingIntervals, intervalInfo)
                }
        }

        if len(missingIntervals) == 0 {
                return nil
        }
```

In essence, we can't generate the metrics without the rewards tree files, but we don't download them because they've already been claimed.
Presumably these files are trivially small and should be downloaded regardless of whether or not they have been claimed.

**Comment by jclapis** [comment]
Fixed in 71b202cf5ec14ec35d9e9dcca041de70567e515e.
