### ISSUE TITLE
Request: add smoothing pool balance to Prometheus and Grafana

### ISSUE THREAD

**Issue by idan88** [rocket-pool/smartnode#259]
Hi,
Can you please have Prometheus  collect and export the current smoothing pool balance in order to display it on the Grafana dashboard?
If you could show my personal upcoming reward share that would be even more awesome :)
Thanks!

**Comment by jclapis** [comment]
Commenting here for posterity: now that the GMC has been ratified, I am planning to make a bounty for an updated Grafana dashboard that includes these. We'll close this issue when it's been completed.
