### ISSUE TITLE
Improve `rocketpool node sync` and `status` sanity checks

### ISSUE THREAD

**Issue by jshufro** [rocket-pool/smartnode#273]
With a fully synced node on prater and a fallback on mainnet, one sees:
![image](https://user-images.githubusercontent.com/116244/206530096-8dd1b9ba-dfd0-442f-8a4f-e16a7910806b.png)

sync/status should validate that the same chain exists on the fallback, when possible

h/t popstar on discord

**Comment by fullmetaleng** [comment]
how does a node end up in this state? when running `rocketpool service config` the first step it asks for is to select a network, doesn't that network apply to both primary and fallaback clients?

**Comment by jshufro** [comment]
> doesn't that network apply to both primary and fallaback clients?

no, the fallback client is generally a separate _machine_, so the primary has no good way of telling it which network it should be syncing.
