### ISSUE TITLE
shared/services/config/external-configs.go - external client URL changes for eth2 does not trigger node/api/watchtower restarts

### ISSUE THREAD

**Issue by jshufro** [rocket-pool/smartnode#284]
https://github.com/rocket-pool/smartnode/blob/master/shared/services/config/external-configs.go 

Taking LH as an example:
```golang
		HttpUrl: config.Parameter{
			ID:                   "httpUrl",
			Name:                 "HTTP URL",
			Description:          "The URL of the HTTP Beacon API endpoint for your external client.\nNOTE: If you are running it on the same machine as the Smartnode, addresses like `localhost` and `127.0.0.1` will not work due to Docker limitations. Enter your machine's LAN IP address instead.",
			Type:                 config.ParameterType_String,
			Default:              map[config.Network]interface{}{config.Network_All: ""},
			AffectsContainers:    []config.ContainerID{config.ContainerID_Eth1},
			EnvironmentVariables: []string{"CC_API_ENDPOINT"},
			CanBeBlank:           false,
			OverwriteOnUpgrade:   false,
		},
```

note that `AffectsContainers` only points to eth1 (which, itself, I'm not sure why)... however, updating this directly impacts, at the very least, rocketpool_api, and possibly also watchtower/node, since they check the BN URL when querying sync status.

The impact of this is that updating an external BN URL causes the eth1 container to restart but the api/node/watchtower services continue to query the old URL. Since the VC has an env variable, it is at least recreated, though it is also absent from the list when exiting the tui:

![image](https://user-images.githubusercontent.com/116244/210155062-e8873675-e7bf-4d8a-b633-61e29ed597a1.png)

![image](https://user-images.githubusercontent.com/116244/210155078-09ff8663-37dd-4d0b-859e-d0385173311f.png)

While we're talking about it, I think `NewExternalExecutionConfig` also wants to restart watchtower

**Comment by 0xfornax** [comment]
Hey @jshufro, I'm working on this. I'm also not sure why eth1 would need to be restarted. Any thoughts @jclapis ?

Also, `NewExternalExecutionConfig`  is already restarting the watchtower.

I checked the code and agree that api/watchtower/node would need to be restarted and also added the validator to warn the user that it is going to be restarted.

**Comment by jshufro** [comment]
I can't think of any change to the beacon node config that would require an eth1 restart.

`NewExternal<Client>Config` should, imo, restart api/node/watchtower only, and only in `HttpUrl:` and `JsonRpcUrl:` fields
