### ISSUE TITLE
Bug when checkpoint syncing on prater

### ISSUE THREAD

**Issue by samlaf** [rocket-pool/smartnode#328]
I tried a few checkpoint providers so far, and they all give me the same error
```
Mar 23 00:01:45.531 INFO Logging to file                         path: "/ethclient/lighthouse/beacon/logs/beacon.log"
Mar 23 00:01:45.532 INFO Lighthouse started                      version: Lighthouse/v3.4.0-38514c0
Mar 23 00:01:45.532 INFO Configured for network                  name: prater
Mar 23 00:01:45.533 INFO Data directory initialised              datadir: /ethclient/lighthouse
Mar 23 00:01:45.533 WARN Running HTTP server on port 5052
Mar 23 00:01:45.534 INFO Deposit contract                        address: 0xff50ed3d0ec03ac01d4c79aad74928bff48a7b2b, deploy_block: 4367322
Mar 23 00:01:45.593 INFO Connected to external block builder     builder_profit_threshold: 0, builder_url: "http://mev-boost:18550/", service: exec
Mar 23 00:01:45.593 INFO Starting checkpoint sync                remote_url: https://prater.checkpoint.sigp.io/, service: beacon
Mar 23 00:01:46.446 WARN Remote BN does not support EIP-4881 fast deposit sync, service: beacon
Mar 23 00:01:47.470 CRIT Failed to start beacon node             reason: Unable to parse SSZ: OffsetSkipsVariableBytes(388). Ensure the checkpoint-sync-url refers to a node for the correct network
Mar 23 00:01:47.470 INFO Internal shutdown received              reason: Failed to start beacon node
Mar 23 00:01:47.470 INFO Shutting down..                         reason: Failure("Failed to start beacon node")
Failed to start beacon node
Mar 23 00:01:48.067 INFO Logging to file                         path: "/ethclient/lighthouse/beacon/logs/beacon.log"
Mar 23 00:01:48.068 INFO Lighthouse started                      version: Lighthouse/v3.4.0-38514c0
Mar 23 00:01:48.068 INFO Configured for network                  name: prater
Mar 23 00:01:48.068 INFO Data directory initialised              datadir: /ethclient/lighthouse
Mar 23 00:01:48.068 WARN Running HTTP server on port 5052
Mar 23 00:01:48.068 INFO Deposit contract                        address: 0xff50ed3d0ec03ac01d4c79aad74928bff48a7b2b, deploy_block: 4367322
Mar 23 00:01:48.120 INFO Connected to external block builder     builder_profit_threshold: 0, builder_url: "http://mev-boost:18550/", service: exec
Mar 23 00:01:48.121 INFO Starting checkpoint sync                remote_url: https://prater.checkpoint.sigp.io/, service: beacon
Mar 23 00:01:48.966 WARN Remote BN does not support EIP-4881 fast deposit sync, service: beacon
Mar 23 00:01:50.217 CRIT Failed to start beacon node             reason: Unable to parse SSZ: OffsetSkipsVariableBytes(388). Ensure the checkpoint-sync-url refers to a node for the correct network
Mar 23 00:01:50.217 INFO Internal shutdown received              reason: Failed to start beacon node
Mar 23 00:01:50.217 INFO Shutting down..                         reason: Failure("Failed to start beacon node")
Failed to start beacon node
```

Seems like this is a bug with smartnode, but hard to tell... here's my lighthouse config.
<img width="835" alt="image" src="https://user-images.githubusercontent.com/9342524/227065653-0430e44b-b95e-4089-8498-9f453c86ee7b.png">

Getting this error regardless of whether I add any additional beacon client flags.

**Comment by jshufro** [comment]
Have you tried a different checkpointz provider? `https://goerli.beaconstate.ethstaker.cc/` has worked well for me in the past.

I'm 99% sure this is not a smartnode issue.

**Comment by samlaf** [comment]
My first sentence says I’ve tried a few (3 if I remember correctly)

**Comment by jshufro** [comment]
Ah. Well, the [Mr. Frundles](https://github.com/sigp/lighthouse/releases/tag/v3.3.0) release of LH from Nov 2022 added a feature that isn't supported by checkpointz.

```
If the checkpoint sync provider does not support the feature you'll see a pair of warning logs:
WARN Remote BN does not support EIP-4881 fast deposit sync
WARN Failed to finalize deposit cache
```

But as you can see, the fallback behavior isn't working for you either:
```
Mar 23 00:01:47.470 CRIT Failed to start beacon node             reason: Unable to parse SSZ: OffsetSkipsVariableBytes(388). Ensure the checkpoint-sync-url refers to a node for the correct network
```

This is because you're probably using smartnode 1.7.5 instead of 1.9.0-rc2, which is the post-shanghai, post-capella beta for smartnode, and is required on Prater test net.

I recommend joining the discord so you get notified about required updates, at least while running a testnet node.

Anyway, run `rocketpool service version` to check your version. If it isn't 1.9.0-rc2, you can install it with ```wget https://github.com/rocket-pool/smartnode-install/releases/download/v1.9.0-rc2/rocketpool-cli-linux-amd64 -O ~/bin/rocketpool``` (assuming x86_64), and then `rocketpool service install -d; rocketpool service start`

Since you're using LH you will want to upgrade the container tag in `rocketpool service config` to `sigp/lighthouse:v4.0.1-rc.0` because LH had a bug with their 4.0.0 release, which is what 1.9.0 will attempt to use.

See the 'releases' channel on discord for more info

**Comment by samlaf** [comment]
That’s very likely exactly what was happening, thank you for letting me know. I followed the instructions on the website though, so there’s probably a command that needs to be updated somewhere.

**Comment by jshufro** [comment]
The docs on the website fall out of sync every hard fork unfortunately. Probably room for improvement there, you're right.
