### ISSUE TITLE
node status threw exception

### ISSUE THREAD

**Issue by cunum** [rocket-pool/smartnode#370]
I have not setup a minipool yet and when running `rocketpool node status` it threw the following exception:

<img width="837" alt="Bildschirm­foto 2023-05-26 um 21 28 16" src="https://github.com/rocket-pool/smartnode/assets/26085773/24c25ca7-b0e5-4b6b-bbbf-ecafddacde8d">

**Comment by 0xfornax** [comment]
Thanks for reporting. Closing as already fixed.
