### ISSUE TITLE
[bug] Starting Nethermind pruning fails for Nethermind 1.25.2

### ISSUE THREAD

**Issue by Blackclaws** [rocket-pool/smartnode#436]
With the recent Nethermind fallout, operators had to upgrade Nethermind to 1.25.2.

However that container only has a Net 8 runtime while the NethermindPruneStarter.dll is still compiled for Net 7 failing to start the prune.

The Smartnode should get an upgrade to instead use the new go based prune starter.

**Comment by jshufro** [comment]
closed by #434
