### ISSUE TITLE
API Additions

### ISSUE THREAD

**Issue by moles1** [rocket-pool/smartnode#46]
The API subcommand will need a number of additional endpoints for the GUI (and potentially other applications) to query:

- [x] Add `canXXX` endpoints for `XXX` commands which mutate state, e.g. `api node canRegister` for `api node register` . This will allow the GUI to check that conditions are correct for performing an action and display appropriate prompts / UI state, without having to attempt to perform it first.

- [x] Add an endpoint to get the node account address (without the registration info like what's returned by `api node status`)

**Comment by darcius** [comment]
Adding to this, a few improvements mostly for the GUI.

`rocketpool api node send [address] [amount] [unit]` - Can this return the TX number if successful?
