### ISSUE TITLE
Support multi node on k8s

### ISSUE THREAD

**Issue by krasi-georgiev** [rocket-pool/smartnode#47]
I asked on discord as well so sorry for the double post.

Are there any docs or manifests for k8s yet or is this on the roadmap?

the main reason for k8s is self-healing - when a node goes down all pods/validators would be rescheduled on another k8s node.

Monitoring - can install the prometheus operator to enable monitoring and alerting.

I am willing to contribute if you would be open to this.

**Comment by krasi-georgiev** [comment]
as a start it would save a lot of time to add simple instructions on just using docker with the compose file and than the if needed the rocketpool command

**Comment by k** [comment]
I would like this too. I'm working on creating a helm chart but the cli is so poorly documented. I can't figure out how to generate a config.

**Comment by krasi-georgiev** [comment]
did you check the api docs?
https://rocket-pool.readthedocs.io/en/latest/smart-node/api.html#the-smart-node-api

**Comment by k** [comment]
Yes I think i stumbled across that but I still don't know how to generate a config. Idk how to configure it to connect to my local geth and prysm nodes.

**Comment by krasi-georgiev** [comment]
I moved to into other directions
