### ISSUE TITLE
Investigate powershell config issues

### ISSUE THREAD

**Issue by moles1** [rocket-pool/smartnode#55]
Powershell users are experiencing problems running `rocketpool service config`; powershell seems to be rewriting the file path: `~\.rocketpool\config.yml`

**Comment by moles1** [comment]
Fixed; now manually joining paths in the CLI instead of using `filepath.Join`

**Comment by rpdb-ops** [comment]
How do you manually join paths in the CLI instead of using filepath.Join ?
