### ISSUE TITLE
[documentation] list of required ports for eth1/eth2/rocketpool to allow for firewall config

### ISSUE THREAD

**Issue by actuallymentor** [rocket-pool/smartnode#59]
Morning!

I would like to harden my node setup a bit more, for which one of the elements if setting up a restrictive firewall on the host machine.

In the docs I can't find [any reference to the word port](https://rocket-pool.readthedocs.io/en/latest/search.html?q=port&check_keywords=yes&area=default) so I guess this is yet to be implemented.

Do you have a list of such ports?

If so can you add them to the docs, or share them here so I can create a pull request on the docs?

If not, is this something you can spend time on or should I do some digging on my own?

**Comment by leontodd** [comment]
The ports are only 'officially' documented in the AWS setup guide (https://medium.com/rocket-pool/rocket-pool-smart-nodes-on-aws-c4d45fa5c9ad). Probably needs to be added to the proper documentation though.

> 30303-30305 TCP/UDP
> 9001 TCP/UDP
> 22 TCP (if SSH is required of course)

On a box with a restrictive firewall and only these ports open, everything works fine.

**Comment by actuallymentor** [comment]
Shall I make a pull request on the documentation?

**Comment by moles1** [comment]
Peer discovery port ranges added to the documentation here: https://rocket-pool.readthedocs.io/en/latest/smart-node/service.html

**Comment by actuallymentor** [comment]
Can you confirm that these are all the ports used?

We're not talking "what's ideally available" but "everything except these are actively blocked".

**Comment by actuallymentor** [comment]
Circling back. I've found the following ports in their respective documentations:

```
# Go Ethereum: https://geth.ethereum.org/docs/interface/private-network#setting-up-networking
ufw allow 30303:30305/tcp comment 'Go Ethereum'
ufw allow 30303:30305/udp comment 'Go Ethereum'

# Teku: https://gist.github.com/Larrypcdotcom/fcd4e79c2cf02ce37ec6ed9797beca2c#ports
ufw allow 9001/tcp 'Eth2 discovery'
ufw allow 9001/udp 'Eth2 discovery'

# Prysm: https://docs.prylabs.network/docs/prysm-usage/p2p-host-ip/#incoming-p2p-connection-prerequisites
ufw allow 13000/tcp comment 'Prysm node'
ufw allow 13000/udp comment 'Prysm node'
```

I have some questions:

- [ ] Is Rocketpool only using `30303` as seems to be the default in the Eth docs or are the others used for anything?
- [ ] Port `9001` is associated with the Teku implementation of the Beaconchain. I can't find a code match for `teku` in this repo, can you confirm this port is for Teku in the RP stack?

**Comment by moles1** [comment]
> Can you confirm that these are all the ports used?
> 
> We're not talking "what's ideally available" but "everything except these are actively blocked".

All of the ports described in the documentation are actively used, yes.

> Is Rocketpool only using 30303 as seems to be the default in the Eth docs or are the others used for anything?

We originally had the docker-compose file set up to bind 30303-30305, but only 30303 is actually required. 30304-30305 are only necessary if you want to run a bootnode, which isn't relevant for RP nodes (and if someone does want to do this they can modify the stack file).

> Port 9001 is associated with the Teku implementation of the Beaconchain. I can't find a code match for teku in this repo, can you confirm this port is for Teku in the RP stack?

Lighthouse and Prysm use different ports for peer discovery by default. We picked 9001 arbitrarily and configured both to use it instead. This way, we always bind the same port to the host regardless of which eth2 client is used.
