### ISSUE TITLE
Running along with existing Geth instance

### ISSUE THREAD

**Issue by Neozaru** [rocket-pool/smartnode#69]
Hi,

I am following this guide : https://medium.com/rocket-pool/rocket-pool-v2-5-beta-node-operators-guide-77859891766b

I am stuck at the step : 
```
Which Eth 1.0 client would you like to run?
1: Geth - made by the Ethereum Foundation
2: Infura - uses infura.io as a light client for Eth 1.0 - not recommended for use in production
```

I already have multiple `geth` instances running on the same server among which one is one the *Goerli* network already and is used as a bridge by an ETH2 medalla validator (also on the same server).
At this point, I am not sure it is a good idea to run a "vanilla" ETH2 validator along with a rocketpool smartnode, but I believe it should not be a problem as long as the validator keys are different.

What I am more concerned about is my existing `geth` running on Goerli. I'd really like to use that one for the rocketpool smartnode but the installation script suggests that it will setup another one, which I don't really want.

Hence I am stuck in the installation script because it is not clear to me what will happen when I select option `1: Geth`.

So I imagine this issue is about either clarifying the fact that a smartnode will spawn an extra `geth` instance or proposing a third option of using an existing `geth` instance as eth1 node. I know you ship some analytics software in the smartnode, and also that it is running inside a Docker container by default - hence connection to an existing `geth` might be more complicated. However it will be resources-saving to be able not to run duplicate nodes. 

EDIT : Tried to select option 1 (running `Geth`). As speculated it does try to spawn a new `Geth` instance and binds to the physical machine port.
```
 ERROR: for rocketpool_eth1  Cannot start service eth1: driver failed programming external connectivity on endpoint rocketpool_eth1 (55dcb2b7fad2806828362a8534d37bf4a5a9fcd19daa7355a3c89b9f3fc79599): Error starting userland proxy: listen tcp 0.0.0.0:30303: bind: address already in use
```
To unstuck it quickly, I ran my existing `geth` instance on a other port using the option `--port <anotherPort>` (I am sure it is possible to change the port on the rocketpool end but I haven't investigated how yet)

**Comment by moles1** [comment]
> At this point, I am not sure it is a good idea to run a "vanilla" ETH2 validator along with a rocketpool smartnode, but I believe it should not be a problem as long as the validator keys are different.

Rocket Pool does its own key management and certain commands will clear and rebuild the validator keystores, so this is a bad idea. If you want to run validators created externally, run them in their own separate validator process (which requires essentially no extra overhead) communicating with the same beacon client. If you need to talk to the RP beacon client, you can edit the `~/.rocketpool/docker-compose.yml` and bind port `5052` to the `eth2` service - then you can reach it at `127.0.0.1:5052`.

> Hence I am stuck in the installation script because it is not clear to me what will happen when I select option 1: Geth.

Rocket Pool will create a docker container with its own running instance of Geth.

> So I imagine this issue is about either clarifying the fact that a smartnode will spawn an extra geth instance or proposing a third option of using an existing geth instance as eth1 node.

Yes, this will be added in future and there is an open issue for it here: https://github.com/rocket-pool/smartnode-install/issues/14

> (I am sure it is possible to change the port on the rocketpool end but I haven't investigated how yet)

You can edit the startup script for the eth1 client at `~/.rocketpool/chains/eth1/start-node.sh`

All in all - your use case is perfectly valid and this has been requested multiple times already, but is not trivial for us to implement. We will get to this at a later time (as per the open issue) once the core features of the stack are more stable.
