### ISSUE TITLE
Custom graffiti option can break command line

### ISSUE THREAD

**Issue by Neozaru** [rocket-pool/smartnode#71]
When the user is prompted to enter a custom graffiti, he can enter whatever value he wants. This value will be incorporated into the start command line with `[...] CUSTOM_GRAFFITI=<value> [...]`.
The problem with that is that some values of the graffiti can break the command line executed when performing `rocketpool service start`.

Reproducing :
- `rocketpool service config`
- On the graffiti prompt, enter `neozaru (2)`
- `rocketpool service start`
```
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `COMPOSE_PROJECT_NAME=rocketpool ETH1_CLIENT=geth ETH1_IMAGE=ethereum/client-go:v1.9.22 ETH2_CLIENT=lighthouse ETH2_IMAGE=sigp/lighthouse:v0.2.13 VALIDATOR_CLIENT=lighthouse VALIDATOR_IMAGE=sigp/lighthouse:v0.2.13 ETH1_PROVIDER=http://eth1:8545 ETH2_PROVIDER=eth2:5052 ETHSTATS_LABEL= ETHSTATS_LOGIN= INFURA_PROJECT_ID= CUSTOM_GRAFFITI=neozaru (2) docker-compose --project-directory ~/.rocketpool -f ~/.rocketpool/docker-compose.yml up -d'
exit status 1
```
It's a minor bug but can be hard to troubleshoot for beginners.

Possible solutions :
- Trimming/escaping user input when he chooses his graffiti.
- Whitelisting the characters allowed in the graffiti.

**Comment by moles1** [comment]
Thanks, nice catch :). This is fixed in https://github.com/rocket-pool/smartnode/commit/8da9b5dfb5ffec047e535894e5627655dd86c1ad and will be merged in soon.
