### ISSUE TITLE
Don't display password on wallet init

### ISSUE THREAD

**Issue by moles1** [rocket-pool/smartnode#75]
The password is currently displayed in clear text on wallet init, and the seed phrase remains on screen after being printed.

**Comment by cincauhangus** [comment]
@moles1 password is also shown when exporting wallet. is this also intended?

**Comment by moles1** [comment]
> @moles1 password is also shown when exporting wallet. is this also intended?

Yes, the wallet keystore isn't useful without it so the password is required to unlock it.

**Comment by moles1** [comment]
Implemented in https://github.com/rocket-pool/smartnode/commit/9b50a2bd71edcb54ad275c435df42a2f9c4df883 and https://github.com/rocket-pool/smartnode/commit/32eb245e60970a18a27129c26bd3ab1c2fc0c857
