### ISSUE TITLE
Invalid Custom Graffiti

### ISSUE THREAD

**Issue by cincauhangus** [rocket-pool/smartnode#77]
I'm trying to add a POAP graffiti to my smart node but it's being rejected as 'invalid custom graffiti'. the graffiti used was generated from https://pyrmont.beaconcha.in/poap.

![image](https://user-images.githubusercontent.com/616127/100537453-d31d5c80-3263-11eb-9e4e-01c3af785999.png)

**Comment by moles1** [comment]
Any custom graffiti entered during config is wrapped like this:
```
RP v0.0.8 (Custom Graffiti)
```
As stated in the prompt, there is a character limit of 16.

If you want to completely customize it, you can modify `~/.rocketpool/chains/eth2/start-validator.sh` and edit the `--graffiti` flag directly.
