### ISSUE TITLE
Node doesn't restart validator service on non-docker setups

### ISSUE THREAD

**Issue by jclapis** [rocket-pool/smartnode#86]
The RP Node has a small incompatibility with setups that run Rocket Pool outside of Docker. After deploying a new minipool, it will attempt to restart the validator container (`restartValidator()` in `rocketpool\node\stake-prelaunch-minipools.go`). However, in these setups, there is no validator container. The call will simply fail with a message in the RP node log.

This probably isn't worth fixing in code because this mode of operation isn't officially supported, but the user should be informed that they need to restart their validator service manually after successfully deploying a minipool. The easiest solution would be to add some documentation to https://rocket-pool.readthedocs.io/en/latest/smart-node/non-docker.html that describes this requirement. It might also be helpful if RP checked for the `--daemon-path` or `-d` flag during a call to `rocketpool node deposit`, and printed a message to the user reminding them to restart the validator service once the minipool has been launched.

**Comment by moles1** [comment]
Good suggestion from @kidkal worth investigating: Create a `restart-validator.sh` shell script in the `.rocketpool` folder and have the node daemon invoke that. Non-docker users can simply edit their restart script to restart their validator service using systemd or similar, rather than docker.
